#!/usr/bin/env ruby
APP_ROOT = File.join(File.dirname(__FILE__), '..')

require 'active_support'
require 'rubigen'
require APP_ROOT + '/config/environment'

ARGV.shift if ['--help', '-h'].include?(ARGV[0])

require 'rubigen/scripts/generate'
RubiGen::Base.use_component_sources!
RubiGen::Scripts::Generate.new.run(ARGV, source: GAMEBOX_PATH + '/component_generators/templates' )
