source "http://rubygems.org"
gem 'require_all'
gem 'tmx'
gem 'pry'
gem 'pry-remote'
gem "gamebox", '>= 0.5.0'
gem "conject"
gem 'chipmunk'

gem "mocha"
gem "rspec"
gem "rspec-core"
gem "rspec-mocks"
gem "rspec-expectations"
gem "rake"
